/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Random;
import modelo.Puntaje;

/**
 *
 * @author Usuario
 */
public class JFrameMain extends javax.swing.JFrame {

    private String idUsuario;
    private int puntajeUsuario;
    private boolean haJugado;
    
     
    
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() { 
        haJugado = false;
        initComponents();
        establecerPuntaje();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPuntos = new javax.swing.JTextField();
        jButtonJugar = new javax.swing.JButton();
        jButtonMejores = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 239, 239));
        jLabel1.setText("Mejor Puntaje: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 36, 190, 30));
        getContentPane().add(jTextFieldPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 110, 40));

        jButtonJugar.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jButtonJugar.setText("Jugar");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 130, 60));

        jButtonMejores.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jButtonMejores.setText("Mejores Puntuaciones");
        jButtonMejores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMejoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMejores, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, -1, -1));

        lblId.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lblId.setForeground(new java.awt.Color(251, 237, 237));
        lblId.setText("jLabel3");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 110, 50));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 237, 237));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 40));

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(251, 237, 237));
        lblUsuario.setText("jLabel3");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Juego3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
personas3x3 p3x3= new personas3x3();//"Frame2" es el nombre que tu le pusiste a tu 2do jframe
p3x3.setVisible(true);
      
        Puntaje puntaje = new Puntaje();
        puntaje.setId_usuario(idUsuario);
        puntaje.setPuntos("" + puntajeUsuario);
        puntaje.crear(puntaje);
        haJugado = true;
        
        
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonMejoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMejoresActionPerformed
        Puntaje punt = new Puntaje();
        punt.consultarMejores();
    }//GEN-LAST:event_jButtonMejoresActionPerformed

   

    public void setIdUsuario(String idUsuario) {
        lblId.setText(idUsuario);
        this.idUsuario = idUsuario;
    }
    
    public void setUsernameUsuario(String idUsuario) {
        lblUsuario.setText(idUsuario);
    }
    
    public String getIdUsuario() {
        System.out.println(idUsuario+"del getter");
        
        return idUsuario;
        
    }
    
    public void establecerPuntaje() {
        Random r = new Random();
        r.ints(1);
        int puntos = r.nextInt() * -1;
        jTextFieldPuntos.setText("" + puntos);
        puntajeUsuario = puntos;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonMejores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldPuntos;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

}
