/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import controlador.Metodos;
/**
 *
 * @author cienriquez
 */
public class personas3x3 extends javax.swing.JFrame {

Metodos metodos = new Metodos();
int RandomPelo = metodos.Random_Pelo();
int RandomPiel = metodos.Random_Piel();
          int contador_preguntas=0;
          
    public personas3x3() {
           initComponents();
            
    }
personaje4x4 persona4 = new personaje4x4();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen1 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JLabel();
        Imagen4 = new javax.swing.JLabel();
        Imagen5 = new javax.swing.JLabel();
        Imagen6 = new javax.swing.JLabel();
        Imagen7 = new javax.swing.JLabel();
        Imagen8 = new javax.swing.JLabel();
        Imagen9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBox_Atributo = new javax.swing.JComboBox<>();
        ComboBox_TipoAtributo = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lcontador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/NB.jpg"))); // NOI18N
        Imagen1.setText("jLabel1");
        Imagen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen1.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen1MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/JB.png"))); // NOI18N
        Imagen2.setText("jLabel2");
        Imagen2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen2.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen2MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, -1, -1));

        Imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/JM.png"))); // NOI18N
        Imagen3.setText("jLabel3");
        Imagen3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen3.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen3MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 0, -1, -1));

        Imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/RN.png"))); // NOI18N
        Imagen4.setText("jLabel4");
        Imagen4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen4.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen4MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, -1, -1));

        Imagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/NM.jpg"))); // NOI18N
        Imagen5.setText("jLabel5");
        Imagen5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen5.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen5MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 231, -1, -1));

        Imagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/RB.png"))); // NOI18N
        Imagen6.setText("jLabel6");
        Imagen6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen6.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen6MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 231, -1, -1));

        Imagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/RM.png"))); // NOI18N
        Imagen7.setText("jLabel7");
        Imagen7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen7.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen7MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 462, -1, -1));

        Imagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/JN.png"))); // NOI18N
        Imagen8.setText("jLabel8");
        Imagen8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen8.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen8MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 462, -1, -1));

        Imagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/NN.jpg"))); // NOI18N
        Imagen9.setText("jLabel9");
        Imagen9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imagen9.setPreferredSize(new java.awt.Dimension(154, 154));
        Imagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen9MouseClicked(evt);
            }
        });
        getContentPane().add(Imagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 462, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/ADQ.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 260, 150));

        ComboBox_Atributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color de pelo", "Color de piel" }));
        ComboBox_Atributo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_AtributoItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboBox_Atributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 300, 60));

        ComboBox_TipoAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Rojo", "Rubio" }));
        getContentPane().add(ComboBox_TipoAtributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 300, 60));
        ComboBox_TipoAtributo.setVisible(false);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mestizo", "Negro", "Blanco" }));
        jComboBox3.setName("");
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 300, 60));
        jComboBox3.setVisible(false);

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jButton1.setText("Pregunta N:");
        jButton1.setActionCommand("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 210, 70));

        lcontador.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        lcontador.setText("0");
        getContentPane().add(lcontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Juego2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    //contador numero de preguntas
        contador_preguntas=contador_preguntas+1;
        lcontador.setText(" "+contador_preguntas);
        if((ComboBox_Atributo.getSelectedIndex())==0){
                       if((ComboBox_TipoAtributo.getSelectedIndex()==0)&&(RandomPelo==0)){
                          Imagen2.setVisible(false);
                          Imagen3.setVisible(false);
                          Imagen4.setVisible(false);
                          Imagen6.setVisible(false);
                          Imagen7.setVisible(false);
                          Imagen8.setVisible(false);
                       }
                        if((ComboBox_TipoAtributo.getSelectedIndex()==1)&&(RandomPelo==1)){
                          Imagen1.setVisible(false);
                          Imagen4.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen6.setVisible(false);
                          Imagen7.setVisible(false);
                          Imagen9.setVisible(false);
                       }
                          if((ComboBox_TipoAtributo.getSelectedIndex()==2)&&(RandomPelo==2)){
                          Imagen1.setVisible(false);
                          Imagen2.setVisible(false);
                          Imagen3.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen8.setVisible(false);
                          Imagen9.setVisible(false);
                       }
                         if((ComboBox_TipoAtributo.getSelectedIndex()==0)&&(RandomPelo!=0)){
                          Imagen1.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen9.setVisible(false);
                          
                       } 
                         if((ComboBox_TipoAtributo.getSelectedIndex()==1)&&(RandomPelo!=1)){
                          Imagen2.setVisible(false);
                          Imagen3.setVisible(false);
                          Imagen8.setVisible(false);
                          
                       } 
                         if((ComboBox_TipoAtributo.getSelectedIndex()==2)&&(RandomPelo!=2)){
                          Imagen4.setVisible(false);
                          Imagen6.setVisible(false);
                          Imagen7.setVisible(false);
                          
                       } 
             
             
        }else{
                        if((jComboBox3.getSelectedIndex()==0)&&(RandomPiel==0)){
                          Imagen1.setVisible(false);
                          Imagen2.setVisible(false);
                          Imagen4.setVisible(false);
                          Imagen6.setVisible(false);
                          Imagen8.setVisible(false);
                          Imagen9.setVisible(false);
                       }
                        if((jComboBox3.getSelectedIndex()==1)&&(RandomPiel==1)){
                          Imagen1.setVisible(false);
                          Imagen2.setVisible(false);
                          Imagen3.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen6.setVisible(false);
                          Imagen7.setVisible(false);
                       }
                          if((jComboBox3.getSelectedIndex()==2)&&(RandomPiel==2)){
                          Imagen3.setVisible(false);
                          Imagen4.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen7.setVisible(false);
                          Imagen8.setVisible(false);
                          Imagen9.setVisible(false);
                       }
                         if((jComboBox3.getSelectedIndex()==0)&&(RandomPiel!=0)){
                          Imagen3.setVisible(false);
                          Imagen5.setVisible(false);
                          Imagen7.setVisible(false);
                          
                       } 
                         if((jComboBox3.getSelectedIndex()==1)&&(RandomPiel!=1)){
                          Imagen4.setVisible(false);
                          Imagen8.setVisible(false);
                          Imagen9.setVisible(false);
                          
                       } 
                         if((jComboBox3.getSelectedIndex()==2)&&(RandomPiel!=2)){
                          Imagen1.setVisible(false);
                          Imagen2.setVisible(false);
                          Imagen6.setVisible(false);
                          
                       } 
             
             
             
             
         }
       
         ComboBox_TipoAtributo.setVisible(false);
           jComboBox3.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void ComboBox_AtributoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_AtributoItemStateChanged
      if((ComboBox_Atributo.getSelectedIndex())==0){
        ComboBox_TipoAtributo.setVisible(true);
        jComboBox3.setVisible(false);
        }else{
        if((ComboBox_Atributo.getSelectedIndex())==1){
            jComboBox3.setVisible(true);
            ComboBox_TipoAtributo.setVisible(false);
        }
         }
    }//GEN-LAST:event_ComboBox_AtributoItemStateChanged

    private void Imagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen9MouseClicked
        if((RandomPelo==0)&&(RandomPiel==1)){
            contador_preguntas=contador_preguntas+1;
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo negro \n piel negra \n Lo lograste en "+contador_preguntas+"intentos" );
            this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen9.setVisible(false);
        }
    }//GEN-LAST:event_Imagen9MouseClicked

    private void Imagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen8MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==1)&&(RandomPiel==1)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rojo \n piel negra \n Lo lograste en "+contador_preguntas+"intentos" );
           this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen8.setVisible(false);
        }
    }//GEN-LAST:event_Imagen8MouseClicked

    private void Imagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen7MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==2)&&(RandomPiel==0)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rubio \n piel mestiza \n Lo lograste en "+contador_preguntas+"intentos" );
             this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen7.setVisible(false);
        }
    }//GEN-LAST:event_Imagen7MouseClicked

    private void Imagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen6MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==2)&&(RandomPiel==2)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rubio \n piel blanca \n Lo lograste en "+contador_preguntas+"intentos" );
               this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen6.setVisible(false);
        }
    }//GEN-LAST:event_Imagen6MouseClicked

    private void Imagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen5MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==0)&&(RandomPiel==0)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo negro \n piel mestizo \n Lo lograste en "+contador_preguntas+"intentos" );
         this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen5.setVisible(false);
        }
    }//GEN-LAST:event_Imagen5MouseClicked

    private void Imagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen4MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==2)&&(RandomPiel==1)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rubio \n piel negra \n Lo lograste en "+contador_preguntas+"intentos" );
             this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen4.setVisible(false);
        }
    }//GEN-LAST:event_Imagen4MouseClicked

    private void Imagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen3MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==1)&&(RandomPiel==0)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rojo \n piel mestiza \n Lo lograste en "+contador_preguntas+"intentos" );
               this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen3.setVisible(false);
        }
    }//GEN-LAST:event_Imagen3MouseClicked

    private void Imagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen2MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==1)&&(RandomPiel==2)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo rojo \n piel blanca \n Lo lograste en "+contador_preguntas+"intentos" );
               this.setVisible(false);
      persona4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen2.setVisible(false);
        }
    }//GEN-LAST:event_Imagen2MouseClicked

    private void Imagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen1MouseClicked
        contador_preguntas=contador_preguntas+1;
        if((RandomPelo==0)&&(RandomPiel==2)){
            JOptionPane.showMessageDialog(null, "Felicitaciones la persona es: \n pelo negro \n piel blanca \n Lo lograste en "+contador_preguntas+"intentos" );
           
      this.setVisible(false);
      persona4.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Error esa no es la persona" );

            lcontador.setText(" "+contador_preguntas);
            Imagen1.setVisible(false);
        }
    }//GEN-LAST:event_Imagen1MouseClicked
//metodos
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personas3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personas3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personas3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personas3x3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // Numeros Random
        //</editor-fold>
        // Numeros Random
        //</editor-fold>
        // Numeros Random
        //</editor-fold>
        // Numeros Random
    
 //mensaje de inicio para ver quien es elegido
     //     JOptionPane.showMessageDialog(null, "PELO:    PIEL:\n 0 Negro    Mestiza \n 1 Rojo    Negra \n 2 Rubio    Blanca \n pelo "+RandomPelo+"   piel"+RandomPiel);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personas3x3().setVisible(true);
            }
        });
    }
    public String marcador1(){
   String respuesta1 =jLabel10.getText();
  return respuesta1; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Atributo;
    private javax.swing.JComboBox<String> ComboBox_TipoAtributo;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel Imagen3;
    private javax.swing.JLabel Imagen4;
    private javax.swing.JLabel Imagen5;
    private javax.swing.JLabel Imagen6;
    private javax.swing.JLabel Imagen7;
    private javax.swing.JLabel Imagen8;
    private javax.swing.JLabel Imagen9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lcontador;
    // End of variables declaration//GEN-END:variables
}
