/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Puntaje;

/**
 *
 * @author cristian
 */
public class personaje4x4 extends javax.swing.JFrame {
//Inicializar 

  boolean [] ver = new boolean[16];
          static int seleccion1=0;
          static int contadorPeguntas;
         static String auxSeleccion2;
    static int seleccion2;
      static ArrayList<Object> lista = new ArrayList<>();
     Integer imagen1[] ={0,0,0,0,1,1};
     Integer imagen2[] ={1,1,2,0,0,1};
     Integer imagen3[] ={2,2,1,0,1,1};
     Integer imagen4[] ={3,0,0,0,0,1};
     Integer imagen5[] ={4,1,2,0,1,1};
                       Integer imagen6[] ={0,2,0,1,0,1};
                       Integer imagen7[] ={1,0,1,1,1,0};
                       Integer imagen8[] ={2,1,2,1,0,1};
                       Integer imagen9[] ={3,2,0,1,1,1};
                       Integer imagen10[] ={4,0,1,1,0,1};
     Integer imagen11[] ={0,1,2,2,1,1};
     Integer imagen12[] ={1,2,1,2,0,1};
     Integer imagen13[] ={2,0,0,2,1,1};
     Integer imagen14[] ={3,1,2,2,0,1};
     Integer imagen15[] ={4,2,1,2,1,0};
                       Integer imagen16[] ={0,0,2,3,0,1};
       
     
     
      
 
        Integer imagenAleatoria[]=null;

  
   
    public personaje4x4() {
        
   
     lista.add(imagen1);
     lista.add(imagen2);
     lista.add(imagen3);
     lista.add(imagen4);
     lista.add(imagen5);
                        lista.add(imagen6);
                        lista.add(imagen7);
                        lista.add(imagen8);
                        lista.add(imagen9);
                        lista.add(imagen10);
     lista.add(imagen11);
     lista.add(imagen12);
     lista.add(imagen13);
     lista.add(imagen14);
     lista.add(imagen15);
                        lista.add(imagen16);
                    
         
     
     ver[0]=true;
     ver[1]=true; 
     ver[2]=true; 
     ver[3]=true;  
     ver[4]=true;
                  ver[5]=true; 
                  ver[6]=true; 
                  ver[7]=true;  
                  ver[8]=true; 
                  ver[9]=true; 
     ver[10]=true;
     ver[11]=true; 
     ver[12]=true; 
     ver[13]=true;  
     ver[14]=true;
                  ver[15]=true; 
   
     
     
        initComponents();
        visible();
        
          jComboBox2.setVisible(true);    
     jComboBox3.setVisible(false);
      jComboBox4.setVisible(false);
       jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
         jComboBox7.setVisible(false);
 
     imagenAleatoria=((Integer[]) lista.get(seleccionarImagenBuscar()));
 
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        etiquetaContador = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/1.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/2.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/3.jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/4.jpg"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/5.jpg"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/6.jpg"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/7.jpg"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/8.jpg"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/9.jpg"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/10.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/11.jpg"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/12.jpg"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/13.jpg"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/14.jpg"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/15.jpg"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes5x5/16.jpg"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jButton1.setText("Pregunta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelo", "Piel", "Ojos", "Ropa", "Sexo", "Lentes" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 210, 60));

        jComboBox2.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Rojo", "Castaño", "Rubio", "Blanco" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        jComboBox3.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanca", "Mestiza", "Negra" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        jComboBox4.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdes", "Azules", "Cafés" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        jComboBox5.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negra", "Café", "Azul", "Verde", " ", " " }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        jComboBox6.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        jComboBox7.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Lentes", "Sin Lentes" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 210, 60));

        etiquetaContador.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        etiquetaContador.setText("0");
        getContentPane().add(etiquetaContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 80, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes3x3/ADQ.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Juego2.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     contadorPeguntas=contadorPeguntas+1;
    seleccion1=jComboBox1.getSelectedIndex();
    etiquetaContador.setText(""+contadorPeguntas);
          
            switch(seleccion1){
                case 0 : seleccion2=jComboBox2.getSelectedIndex();
    auxSeleccion2 = (String) jComboBox2.getSelectedItem();
                       
                break;
                case 1 : seleccion2=jComboBox3.getSelectedIndex();
                 auxSeleccion2=(String) jComboBox3.getSelectedItem();
                break;
                case 2 : seleccion2=jComboBox4.getSelectedIndex();
                  auxSeleccion2=(String) jComboBox4.getSelectedItem();
                break;
                case 3 : seleccion2=jComboBox5.getSelectedIndex();
                  auxSeleccion2=(String) jComboBox5.getSelectedItem();
                  
                break;
                case 4 : seleccion2=jComboBox6.getSelectedIndex();
                  auxSeleccion2=(String) jComboBox6.getSelectedItem();
                break;
                case 5 : seleccion2=jComboBox7.getSelectedIndex();
                auxSeleccion2="";
                break;
               default:JOptionPane.showMessageDialog(null, "no se tiene color de atributo");
            }
      
        comparacion(seleccion1, seleccion2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
           seleccion1=jComboBox1.getSelectedIndex();
            
            switch(seleccion1){
                case 0 : 
                
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(false);
                 jComboBox4.setVisible(false);
                  jComboBox5.setVisible(false);
                   jComboBox6.setVisible(false);
                    jComboBox7.setVisible(false);
                       
                break;
                case 1 :
                 jComboBox3.setVisible(true);
                       jComboBox2.setVisible(false);
                 jComboBox4.setVisible(false);
                  jComboBox5.setVisible(false);
                   jComboBox6.setVisible(false);
                    jComboBox7.setVisible(false);
                break;
                case 2 : 
                 jComboBox4.setVisible(true);
                       jComboBox2.setVisible(false);
                 jComboBox3.setVisible(false);
                  jComboBox5.setVisible(false);
                   jComboBox6.setVisible(false);
                    jComboBox7.setVisible(false);
                break;
                case 3 : 
                 jComboBox5.setVisible(true);
                       jComboBox2.setVisible(false);
                 jComboBox3.setVisible(false);
                  jComboBox4.setVisible(false);
                   jComboBox6.setVisible(false);
                    jComboBox7.setVisible(false);
                break;
                case 4 :
                 jComboBox6.setVisible(true);
                       jComboBox2.setVisible(false);
                 jComboBox3.setVisible(false);
                  jComboBox4.setVisible(false);
                   jComboBox5.setVisible(false);
                    jComboBox7.setVisible(false);
                break;
                case 5 :
                 jComboBox7.setVisible(true);
                       jComboBox2.setVisible(false);
                 jComboBox3.setVisible(false);
                  jComboBox4.setVisible(false);
                   jComboBox5.setVisible(false);
                    jComboBox6.setVisible(false);
                break;
               default:JOptionPane.showMessageDialog(null, "no se tiene color de atributo");
            }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==0)&&
            (imagenAleatoria[1]==0)&&
                (imagenAleatoria[2]==0)&&
                (imagenAleatoria[3]==0)&&
                (imagenAleatoria[4]==1)&&
                (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
               siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              
          jLabel1.setVisible(false);
            
        }
        etiquetaContador.setText(""+contadorPeguntas);
  //          Puntaje puntaje = new Puntaje();
    //    puntaje.setId_usuario(idUsuario);
    //    puntaje.setPuntos("" + puntajeUsuario);
    //    puntaje.crear(puntaje);
     //   haJugado = true;
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
          contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==1)&&
            (imagenAleatoria[1]==1)&&
                (imagenAleatoria[2]==2)&&
                (imagenAleatoria[3]==0)&&
                (imagenAleatoria[4]==0)&&
                (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
          siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
                jLabel2.setVisible(false);
            
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
          contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==2)&&
            (imagenAleatoria[1]==2)&&
                (imagenAleatoria[2]==1)&&
                (imagenAleatoria[3]==0)&&
                (imagenAleatoria[4]==1)&&
                (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
         this.setVisible(false);
          siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
                jLabel3.setVisible(false);
            
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
          contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==3)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==0)&&
           (imagenAleatoria[3]==0)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
              this.setVisible(false);
            siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
                jLabel4.setVisible(false);
            
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==4)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==1)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
          
            this.setVisible(false);
            siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
                jLabel5.setVisible(false);
            
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==0)&&
           (imagenAleatoria[1]==2)&&
           (imagenAleatoria[2]==0)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
          siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel6.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:      contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==1)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==1)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==1)&&
           (imagenAleatoria[5]==0) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
          siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel7.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==2)&&
           (imagenAleatoria[1]==1)&&
           (imagenAleatoria[2]==2)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
            siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel8.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==3)&&
           (imagenAleatoria[1]==2)&&
           (imagenAleatoria[2]==0)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==1)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
    siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel9.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==4)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==1)&&
           (imagenAleatoria[3]==1)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
      siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel10.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==0)&&
           (imagenAleatoria[1]==1)&&
           (imagenAleatoria[2]==2)&&
           (imagenAleatoria[3]==2)&&
           (imagenAleatoria[4]==1)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
      siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel11.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==1)&&
           (imagenAleatoria[1]==2)&&
           (imagenAleatoria[2]==1)&&
           (imagenAleatoria[3]==2)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
             siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel12.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==2)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==0)&&
           (imagenAleatoria[3]==2)&&
           (imagenAleatoria[4]==1)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
            siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel13.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==3)&&
           (imagenAleatoria[1]==1)&&
           (imagenAleatoria[2]==2)&&
           (imagenAleatoria[3]==2)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
    siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel14.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==4)&&
           (imagenAleatoria[1]==2)&&
           (imagenAleatoria[2]==1)&&
           (imagenAleatoria[3]==2)&&
           (imagenAleatoria[4]==1)&&
           (imagenAleatoria[5]==0) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
    siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel15.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
              contadorPeguntas=contadorPeguntas+1;
        //label
        if((imagenAleatoria[0]==0)&&
           (imagenAleatoria[1]==0)&&
           (imagenAleatoria[2]==2)&&
           (imagenAleatoria[3]==3)&&
           (imagenAleatoria[4]==0)&&
           (imagenAleatoria[5]==1) ){
            JOptionPane.showMessageDialog(null, "Felicitaciones encontraste al personaje en "+contadorPeguntas+" Intentos");
             this.setVisible(false);
      siguienteNivel();
        }else{
              JOptionPane.showMessageDialog(null, "Esa no es la persona correcta");
              jLabel16.setVisible(false);
        }
          etiquetaContador.setText(""+contadorPeguntas);
    }//GEN-LAST:event_jLabel16MouseClicked

    public static void siguienteNivel(){
        
        personaje5x5 persona5 = new personaje5x5();
        persona5.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personaje4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personaje4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personaje4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personaje4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personaje4x4().setVisible(true);
            }
        });
    }
    
      public void visible(){
     jLabel1.setVisible(ver[0]);
     jLabel2.setVisible(ver[1]);
     jLabel3.setVisible(ver[2]);
     jLabel4.setVisible(ver[3]);
     jLabel5.setVisible(ver[4]);
         jLabel6.setVisible(ver[5]);
         jLabel7.setVisible(ver[6]);
         jLabel8.setVisible(ver[7]);
         jLabel9.setVisible(ver[8]);
         jLabel10.setVisible(ver[9]);
           jLabel11.setVisible(ver[10]);
           jLabel12.setVisible(ver[11]);
           jLabel13.setVisible(ver[12]);
           jLabel14.setVisible(ver[13]);
           jLabel15.setVisible(ver[14]);
         jLabel16.setVisible(ver[15]);
    
    }
    
     void comparacion(int x, int y){
            Integer [] vectorAuxiliar = null; 
    
          if((imagenAleatoria[x]==y)){
              
               for (int i=0;i<lista.size();i++){
                    
         vectorAuxiliar=(Integer[]) lista.get(i);
                   if(vectorAuxiliar[x]==y){
                  // ver[i]=true;
                   }else{
                        ver[i]=false;
                   }
               }  
              
         if(jComboBox1.getSelectedIndex()==4){JOptionPane.showMessageDialog(null, "El personaje es "+auxSeleccion2);}else{
              JOptionPane.showMessageDialog(null, "El personaje tiene "+ jComboBox1.getSelectedItem()+" "+auxSeleccion2);}
          }else{
                   if(jComboBox1.getSelectedIndex()==4){JOptionPane.showMessageDialog(null, "El personaje no es "+auxSeleccion2);}else{
              JOptionPane.showMessageDialog(null, "El personaje no tiene "+ jComboBox1.getSelectedItem()+" "+auxSeleccion2);}
                   for (int i=0;i<lista.size();i++){
                    
         vectorAuxiliar=(Integer[]) lista.get(i);
                   if(vectorAuxiliar[x]==y){
                   ver[i]=false;
                   }else{
                      //  ver[i]=true;
                   }
               }   
              
              
              
          }
          
                     
     
         
         visible();
          
               
     
    }
      
      public int seleccionarImagenBuscar(){
            int aleatoria=(int)Math.floor(Math.random()*(0-10)+10);
     return aleatoria;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaContador;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
